version: "3.7"

x-backend-image: &build-image
    context: .
    dockerfile: Dockerfile

services:
  app:
    build:
      <<: *build-image
      target: app
    image: ${IMAGE_PATH}/app:${CI_COMMIT_SHORT_SHA}

  web:
    build:
      <<: *build-image
      target: web
    image: ${IMAGE_PATH}/web:${CI_COMMIT_SHORT_SHA}
    networks:
      - default
